import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navigation from '@/components/Navigation';
import Calendar from '@/components/Calendar';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-byzantine-50">
        <Navigation />
        <div className="container mx-auto px-4 md:px-0 flex flex-col md:flex-row gap-6">
          <aside className="md:w-64 shrink-0">
            <Calendar />
          </aside>
          <main className="flex-grow">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
